name: Apply
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  call-oidc-staging:
    name: OIDC
    uses: ./.github/workflows/oidc.yml
    secrets: inherit
    with:
      role-arn: "arn:aws:iam::392017163980:role/core-infra-role-staging"
      role-session-name: "oidc-access-staging"
      aws-region: "eu-west-1"
